version: '3.1'
services:

  ewm-stats:
    build: StatService/
    image: ewm-stats
    ports:
      - "9090:9090"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/StatsDB
      - DB_NAME=StatsDB
      - POSTGRES_USER=maxim
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=StatsDB
      - POSTGRES_USER=maxim
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: MainService/
    image: ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-stats
      - ewm-db
    environment:
      - MAIN_SERVICE_URL=http://StatService:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/MainDB
      - DB_NAME=MainDB
      - POSTGRES_USER=maxim
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=MainDB
      - POSTGRES_USER=maxim
      - POSTGRES_PASSWORD=root
