version: '3.1'
services:
  stats-server:
    build: stats/
    image: kartsev/ewm-stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmstats
      - DB_NAME=ewmstats
      - POSTGRES_USER=maxim
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewmstats
      - POSTGRES_USER=maxim
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewmservice/
    image: kartsev/ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmservice
      - DB_NAME=ewmservice
      - POSTGRES_USER=maxim
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmservice
      - POSTGRES_USER=maxim
      - POSTGRES_PASSWORD=root